name: CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [22.3.4.10, 23.0.4, 23.1.0]
    container:
      image: erlang:${{ matrix.otp }}-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
           apk update
           apk --no-cache upgrade
           apk --no-cache add gcc git libc-dev libc-utils libgcc linux-headers make bash musl-dev musl-utils ncurses-dev pcre2 pkgconf scanelf wget zlib
    - name: Build
      run: rebar3 compile
    - name: Run tests
      run: |
           cat /proc/sys/net/ipv6/conf/all/disable_ipv6
           ip addr add fd96:dcd2:efdb:41c3::10/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::11/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::12/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::13/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::14/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::15/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::16/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::17/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::18/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::19/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::1a/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::20/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::30/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::40/64 dev lo
           ip addr add fd96:dcd2:efdb:41c3::50/64 dev lo
           rebar3 do xref
           rebar3 do ct
